spring.application.name=familyhelpuae
 spring.data.mongodb.uri=mongodb+srv://ayshahira9_db_user:sLmkoFrvidO8WbJH@familyhelp.yiw9m27.mongodb.net/familyhelpuae
#spring.data.mongodb.uri=mongodb://localhost:27017/familyhelpuae
spring.data.mongodb.database=familyhelpuae

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

# Spring Security debug logging
logging.level.org.springframework.security=DEBUG
logging.level.com.familyhelpuae=DEBUG

#remove later
springdoc.api-docs.enabled=true
logging.level.org.springdoc=DEBUG
