package com.familyhelpuae.user.model;

import java.util.List;

/**
 * ### User
 * - userId
 * - name
 * - email
 * - password (hashed)
 * - role (ADMIN / MEMBER)
 * - individualTrustScore
 * - consecutiveBadRatings
 * - totalInteractions
 * - languages spoken
 * - nationality
 * - cultural preferences
 * - verified (boolean)
 */

/**
 * {
 * id: 1
 * name: "A"
 * email: "A@1.e"
 * password: ""
 * phone: +971 508832180
 * verified: true
 * languages Spoken: ["English", "Malayalam"]
 * nationality: "Indian"
 * trust Score: 9.0
 * consecutiveBadRatings: 0
 * totalInteractions: 0
 * List<UserRelationships> relationships;role;
 * profilePictureUrl: ""
 * createdAt: ""
 * updatedAt: ""
 * }
 */
public class UserModel {
    String userID; // autogenerated unique identifier by mongodb
    String name;
    String email;
    String password;
    String phone;
    boolean verified;
    boolean hasAccount;
    boolean newlyRegistered;
    String[] languagesSpoken;
    String[] nationality;
    double trustScore;
    int consecutiveBadRatings;
    int totalInteractions;
    List<UserFamilies> families; // list of families the user is part of, with role (admin or member) in each family
    List<UserRelationships> relationships; // relationships with other users (e.g., father, brother, mother, sister)
    String profilePictureUrl; // we can remove this if you guys want to
    String createdAt;
    String updatedAt;
}

class UserFamilies {
    String familyId; // the id of the family
    String role; // "admin" or "member"
}

class UserRelationships {
    String userId; // the id of the user this relationship is with
    String relationshipType; // e.g., "father", "brother", "mother", "sister"
}