package com.familyhelpuae.user.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import lombok.Data;

@Data
// @EnableMongoAuditing
@Document(collection = "users")
public class User {

    @Id
    private String userID; // autogenerated unique identifier by mongodb

    @Field("firstname")
    private String firstName;

    @Field("lastname")
    private String lastName;

    @Field("email")
    private String email;

    @Field("password")
    private String password;

    @Field("phone")
    private String phone;

    @Field("verified")
    private boolean verified;

    @Field("hasAccount")
    private boolean hasAccount;

    @Field("newlyRegistered")
    private boolean newlyRegistered;

    @Field("languagesSpoken")
    private List<String> languagesSpoken;

    @Field("nationality")
    private List<String> nationality;

    @Field("trustScore")
    private double trustScore;

    @Field("consecutiveBadRatings")
    private int consecutiveBadRatings;

    @Field("totalInteractions")
    private int totalInteractions;

    // list of families the user is part of, with role (admin or member) in each
    // family
    @Field("families")
    private List<UserFamily> families;

    // relationships with other users (e.g., father, brother, mother, sister)
    @Field("relationships")
    private List<UserRelationship> relationships;

    @Field("profilePictureUrl")
    private String profilePictureUrl; // we can remove this if you guys want to

    @CreatedDate
    @Field("createdAt")
    private LocalDateTime createdAt;

    @LastModifiedDate
    @Field("updatedAt")
    private LocalDateTime updatedAt;

    // filter relationships by type and return list of users
    public List<UserRelationship> getRelationshipsByType(String relationshipType) {
        List<UserRelationship> filteredRelationships = new ArrayList<>();
        if (relationshipType != null)
            for (UserRelationship relationship : relationships)
                if (relationship.getRelationshipType().equals(relationshipType))
                    filteredRelationships.add(relationship);

        return filteredRelationships;

    }

    public boolean hasRelationship(String userId) {
        for (UserRelationship relationship : relationships) {
            if (relationship.isRegistered() && relationship.getUserId().equals(userId))
                return true;
        }

        return false;
    }

    public boolean hasRelationship(String userName, String email) {
        for (UserRelationship relationship : relationships) {
            if (relationship.isNonRegistered() && relationship.getName().equals(userName)
                    && relationship.getEmail().equals(email))
                return true;
        }

        return false;
    }

    public UserRelationship updateRelationship(String userID, String relationshipType) {

        for (UserRelationship relationship : relationships)
            if (relationship.getUserId().equals(userID)) {
                relationship.setRelationshipType(relationshipType);
                return relationship;
            }

        return null;
    }

    public UserRelationship updateRelationship(String userName, String email, String relationshipType) {

        for (UserRelationship relationship : relationships)
            if (relationship.isNonRegistered() && relationship.getName().equals(userName)
                    && relationship.getEmail().equals(email)) {
                relationship.setRelationshipType(relationshipType);
                return relationship;
            }

        return null;
    }

    public UserRelationship deleteRelationship(String userID) {

        Iterator<UserRelationship> iterator = relationships.iterator();

        while (iterator.hasNext()) {
            UserRelationship relationship = iterator.next();
            if (relationship.getUserId().equals(userID)) {
                iterator.remove();
                return relationship;
            }
        }
        return null;
    }

    public UserRelationship deleteRelationship(String userName, String email) {

        Iterator<UserRelationship> iterator = relationships.iterator();

        while (iterator.hasNext()) {
            UserRelationship relationship = iterator.next();
            if (relationship.isNonRegistered() && relationship.getName().equals(userName)
                    && relationship.getEmail().equals(email)) {
                iterator.remove();
                return relationship;
            }
        }
        return null;
    }

    public boolean hasFamily(String familyId) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'hasFamily'");
    }

    public void deleteFamily(String familyId) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'deleteFamily'");
    }

    public void updateFamily(String familyId, String role) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'updateFamily'");
    }
}