/**
 * Section: 104
 * Group number: 4
 * Student IDs and names: 
 * Laisa Sanjida Isra: 1089635
 * Fatima Syed Wasti: 1095190
 * Aysha Hira: 1088000
 */

package com.familyhelpuae.user.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import jakarta.validation.constraints.NotBlank;
import lombok.Data;

@Data
// @EnableMongoAuditing
@Document(collection = "users")
public class User {

    @Id
    private String userID; // autogenerated unique identifier by mongodb

    @NotBlank(message = "First name is required")
    @Field("firstname")
    private String firstName;

    @NotBlank(message = "Last name is required")
    @Field("lastname")
    private String lastName;

    @Indexed(unique = true)
    @Field("email")
    @NotBlank(message = "Email is required")
    private String email;

    @Field("password")
    @NotBlank(message = "Password is required")
    private String password;

    @Field("phone")
    @NotBlank(message = "Phone number is required")
    private String phone;

    @Field("verified")
    private boolean verified;

    @Field("hasAccount")
    private boolean hasAccount;

    @Field("newlyRegistered")
    private boolean newlyRegistered;

    @Field("languagesSpoken")
    private List<String> languagesSpoken = new ArrayList<>();

    @Field("nationality")
    private List<String> nationality = new ArrayList<>();

    @Field("trustScore")
    private double trustScore;

    @Field("consecutiveBadRatings")
    private int consecutiveBadRatings;

    @Field("totalInteractions")
    private int totalInteractions;

    // list of families the user is part of, with role (admin or member) in each
    // family
    @Field("families")
    private List<UserFamily> families = new ArrayList<>();

    // relationships with other users (e.g., father, brother, mother, sister)
    @Field("relationships")
    private List<UserRelationship> relationships = new ArrayList<>();

    @Field("profilePictureUrl")
    private String profilePictureUrl; // we can remove this if you guys want to

    @CreatedDate
    @Field("createdAt")
    private LocalDateTime createdAt;

    @LastModifiedDate
    @Field("updatedAt")
    private LocalDateTime updatedAt;

    // filter relationships by type and return list of users
    public List<UserRelationship> getRelationshipsByType(String relationshipType) {
        List<UserRelationship> filteredRelationships = new ArrayList<>();
        if (relationshipType != null)
            for (UserRelationship relationship : relationships)
                if (relationship.getRelationshipType().equals(relationshipType))
                    filteredRelationships.add(relationship);

        return filteredRelationships;

    }

    public boolean hasRelationship(String userId) {
        for (UserRelationship relationship : relationships) {
            if (relationship.isRegistered() && relationship.getUserId().equals(userId))
                return true;
        }

        return false;
    }

    public boolean hasRelationship(String userName, String email) {
        for (UserRelationship relationship : relationships) {
            if (relationship.isNonRegistered() && relationship.getName().equals(userName)
                    && relationship.getEmail().equals(email))
                return true;
        }

        return false;
    }

    public UserRelationship updateRelationship(String userID, String relationshipType) {

        for (UserRelationship relationship : relationships)
            if (relationship.getUserId().equals(userID)) {
                relationship.setRelationshipType(relationshipType);
                return relationship;
            }

        return null;
    }

    public UserRelationship updateRelationship(String userName, String email, String relationshipType) {

        for (UserRelationship relationship : relationships)
            if (relationship.isNonRegistered() && relationship.getName().equals(userName)
                    && relationship.getEmail().equals(email)) {
                relationship.setRelationshipType(relationshipType);
                return relationship;
            }

        return null;
    }

    public UserRelationship deleteRelationship(String userID) {

        Iterator<UserRelationship> iterator = relationships.iterator();

        while (iterator.hasNext()) {
            UserRelationship relationship = iterator.next();
            if (relationship.getUserId().equals(userID)) {
                iterator.remove();
                return relationship;
            }
        }
        return null;
    }

    public UserRelationship deleteRelationship(String userName, String email) {

        Iterator<UserRelationship> iterator = relationships.iterator();

        while (iterator.hasNext()) {
            UserRelationship relationship = iterator.next();
            if (relationship.isNonRegistered() && relationship.getName().equals(userName)
                    && relationship.getEmail().equals(email)) {
                iterator.remove();
                return relationship;
            }
        }
        return null;
    }

    public boolean hasFamily(String familyId) {
        for (UserFamily family : families) {
            if (family.getFamilyId().equals(familyId))
                return true;
        }

        return false;
    }

    public void updateFamily(String familyId, String role) {
        for (UserFamily family : families)
            if (family.getFamilyId().equals(familyId)) {
                family.setRole(role);
                return;
            }
    }

    public void deleteFamily(String familyId) {
        Iterator<UserFamily> iterator = families.iterator();

        while (iterator.hasNext()) {
            UserFamily family = iterator.next();
            if (family.getFamilyId().equals(familyId)) {
                iterator.remove();
                return;
            }
        }
    }

    public User() {

    }

}