package com.familyhelpuae.request.model;

public class Request {
    String requestId; // autogenerated unique identifier by mongodb
    String requestingFamilyId; // the family that made the request
    String requestingUserId; // the user that made the request
    String requestDescription; // details about the help needed
    String location;
    String requestType; // e.g., "help_request", "volunteer_opportunity", "resource_request"
    String urgencyLevel; // e.g., "low", "medium", "high"
    String requestStatus; // e.g., "open", "matched", "completed", "cancelled"
    String createdAt; // when the request was made
    String updatedAt; // when the request record was last updated
}
