package com.familyhelpuae.offer.model;

public class Offer {
    String offerId; // autogenerated unique identifier by mongodb
    String offeringFamilyId; // the family that made the offer
    String offeringUserId; // the user that made the offer
    String offerType; // e.g., "help_offer", "volunteer_offer", "resource_offer"
    String offerLocation;
    String availability; // e.g., "weekends", "weekdays", "specific dates"
    String offerDescription; // details about the help being offered
    String offerStatus; // e.g., "open", "accepted", "rejected", "cancelled"
    String createdAt; // when the offer was made
    String updatedAt; // when the offer record was last updated
}
